version: '3'

services:
  app:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
     - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data