version: '3'

services:
  
  app:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/
    
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
     - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  react-app:
    build:
      context: ./reactApp
      dockerfile: Dockerfile
    volumes:
      - ./reactApp:/app/
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true
